### ISSUE TITLE
Wrong value type "object"

### ISSUE THREAD

**Issue by cleitonjar** [2do2go/json-sql#10]
My object event:
"payload": {
    "cpf": "12345678990",
    "id": ""
 }

My build:
var sql = jsonSql.build({
  type: 'insert',
  table: 'perfis_'+event.operation,
  values: event.payload //object
}).query;

Stacktrace:
Error: Wrong value type "object"
    at Builder._pushValue (/var/task/node_modules/json-sql/lib/builder.js:55:9)
    at /var/task/node_modules/json-sql/lib/dialects/base/blocks.js:188:26
    at Dialect.buildBlock (/var/task/node_modules/json-sql/lib/dialects/base/index.js:323:9)
    at /var/task/node_modules/json-sql/lib/dialects/base/blocks.js:357:21
    at Function._.map._.collect (/var/task/node_modules/underscore/underscore.js:164:24)
    at _.(anonymous function) [as map] (/var/task/node_modules/underscore/underscore.js:1484:34)
    at /var/task/node_modules/json-sql/lib/dialects/base/blocks.js:356:22
    at Function._.map._.collect (/var/task/node_modules/underscore/underscore.js:164:24)
    at _.(anonymous function) [as map] (/var/task/node_modules/underscore/underscore.js:1484:34)
    at /var/task/node_modules/json-sql/lib/dialects/base/blocks.js:355:27

**Comment by artzhuchka** [comment]
It seems to me that your payload object has some other field with `object` type. I made two test cases:
1) Without `object` field, works well:
```js
var payload = {cpf: '12345678990', id: ''};
builder.build({type: 'insert', table: 'a', values: payload})
// query: 'insert into "a" ("cpf", "id") values ($p1, $p2);'
// values: { p1: '12345678990', p2: '' }
```

2) With `object` field, got similar error:
```js
var payload = {cpf: '12345678990', id: '', test: {}};
builder.build({type: 'insert', table: 'a', values: payload})
// Error: Wrong value type "object"
```

**Comment by artzhuchka** [comment]
Please, try to debug your payload object value, I think it has fields that you didn't explain above.
As workaround of your problem I can advise you to specify `fields` array in the insert query:
```js
var payload = {cpf: '12345678990', id: '', test: {}};
builder.build({type: 'insert', table: 'a', fields: ['cpf', 'id'], values: payload});
// query: 'insert into "a" ("cpf", "id") values ($p1, $p2);'
// values: { p1: '12345678990', p2: '' }
```

**Comment by cleitonjar** [comment]
Hi,
In my all json an attribute as created_at was with new Date(), and in this case is an object. I used lib moment.js for format to string.
My sugestion would be to ignore "object" or use .toString() on json-sql.
Thanks.
Working!
