### ISSUE TITLE
Insert into multiple tables?

### ISSUE THREAD

**Issue by roowilliams** [2do2go/json-sql#16]
Hello, I can't figure out the recommended way using this module to insert into multiple tables at once.

Eg. I have a chat msg from a user, I want to insert into the users table data about the user, and the msg into the msgs table at the same time.

Eg.

```
START TRANSACTION;
INSERT INTO table1 VALUES ('1','2','3');
INSERT INTO table2 VALUES ('bob','smith');
COMMIT;
```

Thanks!

Roo

**Comment by okv** [comment]
Hi, json-sql api translates one json query to one sql query.
Assumes that other things will be done outside of this module.
