### ISSUE TITLE
Is there any way to use Top N records in MS SQL

### ISSUE THREAD

**Issue by renjita** [2do2go/json-sql#18]
Is there any way to use Top N records in MS SQL

for example : **Select Top 10 userid, username from User;** 

Is limit keyword defined only for MySql

Please suggest... 👍

**Comment by okv** [comment]
Current mssql dialect implementation doesn't support top syntax.
Currently it's base dialect child without mssql specific.

**Comment by artzhookov** [comment]
We have not enough time to support all dialects.
If you need "top" or any other keyword, you able to do a pull-request and we will be happy to accept it.
Thanks :-)
