### ISSUE TITLE
how to build sql with "OR", "LIKE" word.

### ISSUE THREAD

**Issue by flowercodec** [2do2go/json-sql#32]
example:
SELECT a FROM table WHERE b = 1 OR c = 1
SELECT a FROM table WHERE b = 1 AND c = 1 AND (d like "dd" OR e like "ee")

**Comment by artzhookov** [comment]
1) 
```js
builder.build({
  type: 'select',
  table: 'table',
  fields: ['a'],
  condition: {
    $or: [
      { b: 1 },
      { c: 1 }
    ]
  }
});
```

2) 
```js
builder.build({
    type: 'select',
    table: 'table',
    fields: ['a'],
    condition: {
        b: 1,
        c: 1,
        $or: [
          { d: { $like: 'dd' } },
          { e: { $like: 'ee' } }
        ]
    }
});
```

**Comment by flowercodec** [comment]
Thanks
first one worked.
second seem something error.
sql.query show follow
select "a" from "table" where "b" = 1 and "c" = 1 and ("d" like $p1 or "e" like $p2);
$p1 $p2  replace the 'dd' and 'ee'

**Comment by flowercodec** [comment]
miss separatedValues : false option

**Comment by artzhookov** [comment]
OK, but it is not safe coz `separatedValues: false` enable potential SQL injections.

**Comment by flowercodec** [comment]
if set separatedValues : true, how to use sql text with "$p1 $p2" ,I use node msql(npm install mysql)
I didn't want potential SQL injections. :(
