### ISSUE TITLE
mysql: Invalid query generated when there is a . in the table name

### ISSUE THREAD

**Issue by ThisIsRuddy** [2do2go/json-sql#37]
I am having issues generating valid mysql query when there is a . used in the table name.
```
        let jsonSql = require('json-sql')({
            dialect: 'mysql'
        });
        let sql = jsonSql.build({
            type: 'select',
            table: this.table,
            condition: {
                KundenNR: kundenNr
            }
        });
        console.log(sql.query);
```
Output:
```select * from `dbo`.`clients` where `KundenNR` = $p1;```
Expected Output:
```select * from `dbo.clients` where `KundenNR` = $p1;```

**Comment by artzhookov** [comment]
You can't use the dot in a database name. Also, I'd avoid using it in any identifier.
Dot is used as separator in json-sql, in other words it's a "special character".
This means that your second output can not be obtained as json-sql result.
