### ISSUE TITLE
How to use the modulo operator with json-sql?

### ISSUE THREAD

**Issue by a1300** [2do2go/json-sql#42]
Is it possible to use the `MODULO` operator (`%` or `MOD()`) with __json-sql__?

I need something like this (find all even block heights):
```sql
select *
from blocks
where height % 2 = 0
```

I searched the code and the tests I couldn't find it.

Thanks in advance!
Kind regards
a1300

**Comment by artzhookov** [comment]
@a1300 you can do this with `$expression` block:

```js
const builder = require('json-sql')();

var sql = builder.build({
    table: 'block',
    condition: {
        $expression: {
            pattern: '{column} % {modulo}',
            values: {
                column: {
                    field: 'height'
                },
                modulo: 2
            },
            $eq: 0
        }
    }
});
```

There no documentation for conditions =( It would be great to fill such gaps in documentation, isn't it? @okv @RoobinGood 
Anyways, some information about expressions could be found here: https://github.com/2do2go/json-sql/tree/master/docs#expression

**Comment by a1300** [comment]
@artzhookov thanks for the answer! :+1:
