### ISSUE TITLE
Advance group by

### ISSUE THREAD

**Issue by freeart** [2do2go/json-sql#7]
Hello! I have a hard sql query. This is part of sql
group by (cast(height / $delegates as integer) + (case when height % $delegates > 0 then 1 else 0 end)) having height <= $height

I made something like that:
group: {
    expression: "(cast(height / $delegates as integer) + (case when height % $delegates > 0 then 1 else 0 end))",
    having: {
        height: {$lte: height}
    }
}

Can you add this feature, I can´t make this.

**Comment by artzhuchka** [comment]
Thanks for your suggestion. I will implement this functionality soon.

**Comment by anuragagarwal561994** [comment]
Also to add to this, mostly the group by queries are grouping of fields or field calculations itself, so will be a good idea to include a group key and boolean value in the field itself?

Adding to this there can also be a group key on its own, something like:
```javascript
const sql = jsonSQL.build({
    type: 'select',
    table: 'table',
    fields: [
        {
            func: {
                name: 'year',
                args: ['column1']
            },
            grouped: true
        },
    ],
    group: ['column2']
});
```

**Comment by aravindiiitb** [comment]
@artzhookov did you get chance to implement the aggregations ?
