### ISSUE TITLE
MSSQL Connection

### ISSUE THREAD

**Issue by ralphievolt** [2do2go/json-sql#8]
I'm new to NPM so please bear with me.. Can this be used for my MS SQL DB? If yes, how do connect my application using your package? I do not see in the documents on how to connect it.

Thanks.

**Comment by okv** [comment]
Hi.
[json-sql](https://github.com/2do2go/json-sql) is query mapper, not a db driver, it converts json queries to sql statements.
So in your application you can get some ms sql driver (e.g. [node-mssql](https://github.com/patriksimek/node-mssql)), json-sql, write your own helper functions (models layer, etc) in which you pass json, convert it to sql using json-sql and execute in db using driver.
